### ISSUE TITLE
cant write to file

### ISSUE THREAD

**Issue by myoung34** [WTFox/pg_compare#4]
using `-o file.csv` or `--outfile foo`:

```

Retrieving details for all tables. This could take awhile... OK
Comparing catalogs... FAIL
Comparing columns... OK
Comparing indexes... OK
Comparing pks... FAIL
Comparing rowcounts... OK
Comparing tables... FAIL
Building report...Traceback (most recent call last):
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/bin/pg-compare", line 11, in <module>
    load_entry_point('pg-compare==0.0.1', 'console_scripts', 'pg-compare')()
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/pg_compare/cli.py", line 49, in cli
    compare_functions.run(config.available_tests)
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/pg_compare/compare_functions.py", line 61, in run
    error_report.build_report()
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/pg_compare/reports.py", line 48, in build_report
    click.echo("Building report...", nl="")
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/local/lib/python2.7/dist-packages/pg_compare/reports.py", line 71, in _create_file
    if not os.path.exists(os.path.dirname(filename)):
  File "/home/ec2-user/.local/share/virtualenvs/pg_compare-qS6FQs44/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''
```

**Comment by WTFox** [comment]
> `No such file or directory: ''`

Two things could be the culprit here:
1) I think pg-compare expects an absolute path (will document this). So if you gave it just the filename it would probably error out trying to split into path and filename. 

or 
2) the user doesn't have write access to the directory they're wanting the log file to be created in.

**Comment by myoung34** [comment]
it was probably the former, i definitely had permissions. i gave it just a file name thinking it would be relative
