### ISSUE TITLE
error on execution

### ISSUE THREAD

**Issue by Danieler** [WTFox/pg_compare#6]
when i try to execute on mac it gives me the following error
` pg-compare --help
Traceback (most recent call last):
  File "/Users/daniel/Library/Python/3.9/bin/pg-compare", line 5, in <module>
    from pg_compare import cli
  File "/Users/daniel/Library/Python/3.9/lib/python/site-packages/pg_compare/__init__.py", line 16, in <module>
    from .config import config
  File "/Users/daniel/Library/Python/3.9/lib/python/site-packages/pg_compare/config.py", line 15, in <module>
    from models import AttributeContainer
ModuleNotFoundError: No module named 'models'`

**Comment by WTFox** [comment]
Hello! Thanks for the issue! Unfortunately, this project is no longer maintained and likely only works for Python 2. Unfortuntely, I don't have the capacity right now to update this but I would graciously accept pull requests!
